"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rrap_mds_is_prov_api
from rrap_mds_is_prov_api.api.model_runs_api import ModelRunsApi  # noqa: E501


class TestModelRunsApi(unittest.TestCase):
    """ModelRunsApi unit test stubs"""

    def setUp(self):
        self.api = ModelRunsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_register_complete_model_run(self):
        """Test case for register_complete_model_run

        Register Model Run Complete  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
