"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_prov_api
from rrap_mds_is_prov_api.model.provenance_record_info import ProvenanceRecordInfo
from rrap_mds_is_prov_api.model.status import Status
globals()['ProvenanceRecordInfo'] = ProvenanceRecordInfo
globals()['Status'] = Status
from rrap_mds_is_prov_api.model.register_model_run_response import RegisterModelRunResponse


class TestRegisterModelRunResponse(unittest.TestCase):
    """RegisterModelRunResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegisterModelRunResponse(self):
        """Test RegisterModelRunResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegisterModelRunResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
