"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_prov_api
from rrap_mds_is_prov_api.model.model_run_record import ModelRunRecord
globals()['ModelRunRecord'] = ModelRunRecord
from rrap_mds_is_prov_api.model.provenance_record_info import ProvenanceRecordInfo


class TestProvenanceRecordInfo(unittest.TestCase):
    """ProvenanceRecordInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProvenanceRecordInfo(self):
        """Test ProvenanceRecordInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProvenanceRecordInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
