"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rrap_mds_is_prov_api
from rrap_mds_is_prov_api.api.explore_lineage_api import ExploreLineageApi  # noqa: E501


class TestExploreLineageApi(unittest.TestCase):
    """ExploreLineageApi unit test stubs"""

    def setUp(self):
        self.api = ExploreLineageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_explore_downstream(self):
        """Test case for explore_downstream

        Explore Downstream  # noqa: E501
        """
        pass

    def test_explore_upstream(self):
        """Test case for explore_upstream

        Explore Upstream  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
